"""Regenerate the Markdown report from the latest live outputs.

This script exists for workflow symmetry. The main report is generated by
run_backtest.py because it has access to the full in-memory result object.
"""

from pathlib import Path


def main() -> None:
    report = Path("reports/live/strategy_report.md")
    if report.exists():
        print(f"Report already exists: {report}")
    else:
        raise FileNotFoundError("Run python scripts/run_backtest.py first.")


if __name__ == "__main__":
    main()

